server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sab17
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: sab17-order-service

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: my-product
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.JsonSerializer

# Actuator (for health checks and metrics)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4j for Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      myService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
